config/routes.rb
Rails.application.routes.draw do
  resources :admins, only: [:create, :show, :new]
  root 'main#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_many :developers, dependent: :destroy
  validates :login_id, presence: true, length: {minimum: 6, maximum: 16}, uniqueness: { case_sensitive: false }
  validates :name,     presence: true, length: {minimum: 2, maximum: 20}
  validates :password, presence: true, length: {minimum: 4, maximum: 20}
end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :developer
  has_many :customers, through: :licenses
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :applications, through: :licenses
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  belongs_to :admin
  has_many :applications, dependent: :destroy
end

app/models/license.rb
class License < ActiveRecord::Base
  belongs_to :customer
  belongs_to :application
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def show
    @admin = Admin.find(params[:id])
  end

  def new
    @admin = Admin.new
  end
  def create
    admin = Admin.new(admin_params)
    if admin.save
      redirect_to root_path
    else
      render :new
    end
  end
  private 
  def admin_params
    require(:admin).permit(:name, :login_id, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/admins/new.html.erb
<%= form_for(@admin) do |f| %>
<%= f.label :login_id %>
<%= f.text_field :login_id %>
<%= f.submit '登録' %>
<% end %>

app/views/layouts/_header.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default header">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	<span class="sr-only">Toggle navigation</span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Project name</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
	<li><a href="#">Home</a></li>
	<li><a href="#">About</a></li>
	<li><%= link_to new_admin_path do %>新規アカウント<% end %></li>
	<li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
	  <ul class="dropdown-menu" role="menu">
	    <li><a href="#">Action</a></li>
	    <li><a href="#">Another action</a></li>
	    <li><a href="#">Something else here</a></li>
	    <li class="divider"></li>
	    <li class="dropdown-header">Nav header</li>
	    <li><a href="#">Separated link</a></li>
	    <li><a href="#">One more separated link</a></li>
	  </ul>
	</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
	<li><a href="./">Default <span class="sr-only">(current)</span></a></li>
	<li><a href="../navbar-static-top/">Static top</a></li>
	<li><a href="../navbar-fixed-top/">Fixed top</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/layouts/_side.html.erb
<ul class="nav nav-pills nav-stacked side">
  <li><a href="#">ダッシュボード</a></li>
  <li><a href="#">サーバー１</a></li>
  <li><a href="#">サーバー２</a></li>
  <li><a href="#">サーバー３</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
  </div>
  <div class="container">
    <div class="row main">      
      <div class="col-xs-2">
	<%= render 'layouts/side' %>
      </div>  
      <div class="col-xs-10">
	<%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/main/index.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <div class="panel-title">sv-01</div>
  </div>
  <div class="panel-body">サーバー１のステータスOK</div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <div class="panel-title">sv-02</div>
  </div>
  <div class="panel-body">サーバー２のステータスOK</div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <div class="panel-title">sv-03</div>
  </div>
  <div class="panel-body">サーバー３のステータスOK</div>
</div>